// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpV7Gs-Xfl_DWj0dJFJJliDegWFSu-MlM',
    appId: '1:151425170012:web:78cc0078aeba216f250499',
    messagingSenderId: '151425170012',
    projectId: 'porfolio-7d21b',
    authDomain: 'porfolio-7d21b.firebaseapp.com',
    storageBucket: 'porfolio-7d21b.firebasestorage.app',
    measurementId: 'G-DTY4LFEPPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd4-Xafl1pvSfSC_KvAQ47NIC_P1W-N80',
    appId: '1:151425170012:android:4646b0b15253ae8d250499',
    messagingSenderId: '151425170012',
    projectId: 'porfolio-7d21b',
    storageBucket: 'porfolio-7d21b.firebasestorage.app',
  );
}
